Extend syntax with setting [priority] of task
leibler/dokuwiki-plugin-todo pull request #133
Opened 2021-06-05 09:54 UTC by greeneng

I extended syntax of Todo plugin for my project (but probably from older version).
Features: add 1, 2 or 3 exclamation marks (!) into <todo> tag to set priority.
When rendered this option just adds a class to <span class="todotext ..."> 
Example 1: <todo !>low priority task</todo>
Example 2: <todo !!!>high priority task</todo>

2023-02-22 17:00 UTC, einhirn requested changes
Please address the comments I added to the code.

2023-05-31 09:04 UTC, einhirn commented
Do you still want this to be merged? Please address the requested changes and resolve the conflicts. Otherwise I'll probably close this PR in 1-3 Months or so...

2023-08-08 09:34 UTC, greeneng commented
I've updated files in pull request

2023-08-08 15:14 UTC, einhirn commented on syntax/todo.php
> -        }
Probably just because the PR currently still is based on our code 12 commits ago...

2023-08-08 15:30 UTC, einhirn commented
@greeneng Please rebase your pull request onto our main branch. In your own git repo do the following to clean up your git log of non-descript commits and get your fork up to date with this repo in one go:
```
git add remote upstream https://github.com/leibler/dokuwiki-plugin-todo.git
git fetch upstream
git checkout master
git rebase --interactive upstream/main
vi/nano/whatever <conflicted file>
git add <conflicted file>
git rebase --continue
# rinse repeat
``` 

It will probably fail with conflicts, but it will tell you what to do. Of course you'll need to adjust the conflicted files so your new code is actually added to the already existing code...
There are helpful manuals like this out there:
https://docs.github.com/en/get-started/using-git/about-git-rebase

and it links to pages about what to do when there are conflicts during a rebase:
https://docs.github.com/en/get-started/using-git/resolving-merge-conflicts-after-a-git-rebase
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line

2023-08-08 17:03 UTC, closed without merging