Extend syntax with setting [priority] of task
leibler/dokuwiki-plugin-todo pull request #157
Opened 2023-08-08 19:57 UTC by greeneng

I extended syntax of Todo plugin for my project (but probably from older version).
Features: add 1, 2 or 3 exclamation marks (!) into tag to set priority.
When rendered this option just adds a class to
Example 1: <todo !>low priority task
Example 2: <todo !!!>high priority task

Re-made from scratch

2023-08-09 06:50 UTC, einhirn commented on syntax/todo.php
> +				if (($plen == $excl_count) && ($plen >= 0) && ($plen <= 3))
Should four or more exclamation marks really mean priority 0 or should that be mapped to priority 3? I think it's good that your code is really picky about what it handles - like not parsing `!!1` as a priority - but I wonder whether this conforms to a policy of least astonishment...

2023-08-09 06:54 UTC, einhirn commented
@runout-at what's your take on the lines I commented on? And if it's just the commit history and the tabs of this PR, I could manually merge it, adjusting it accordingly. Don't want to be too hard on a first time contributor 😁

2023-08-10 09:16 UTC, greeneng commented on syntax/todo.php
> +				if (($plen == $excl_count) && ($plen >= 0) && ($plen <= 3))
made four or more '!' to be parsed as high priority, but things like `!!11aaaa1!!!` will be ignored.

2023-08-10 09:17 UTC, greeneng commented
> Don't want to be too hard on a first time contributor

You can be, I need too learn ;-)

2023-08-10 10:21 UTC, einhirn commented on syntax/todo.php.orig
Please remove this additional file.

2023-08-10 10:23 UTC, einhirn commented on syntax/todo.php
> +
Missed one tab. Do you know "git diff"? It shows uncommitted changes and will highlight space-to-tab changes etc.

2023-08-10 10:37 UTC, einhirn commented on syntax/todo.php
> +                if (isset($handler) && !is_null($handler))
I wonder where this `if`-clause comes from and/or what it's purpose is...

2023-08-10 10:45 UTC, einhirn commented on syntax/todo.php
> +                if (isset($handler) && !is_null($handler))
Looking at the additional "syntax/todo.php.orig"-file, this if clause is a leftover from older versions. Please remove it again, we're safeguarding against variables not being set by explicitly setting them above...

2023-08-10 10:53 UTC, greeneng commented on syntax/todo.php
> +
Hmm, for me it showed 4 spaces before \n
fixed

2023-08-10 10:54 UTC, einhirn commented
> > Don't want to be too hard on a first time contributor
> 
> You can be, I need too learn ;-)

ok, so what environment are you using to work on the code? All those "add file via upload" commit messages look like you're not using git on your own system? Otherwise you'd group discrete changes to commits with meaningful commit messages.

Just saw your latest commit message: That's more like it.

Also with "rebasing" there's a way to reduce the number of commits, so the commit history of this repo doesn't get cluttered with all those "added file via upload"-messages. I gave some pointers in your previous PR, but it probably requires you to clone the repo to your computer and use `git` on that clone - maybe with some kind of GUI, or maybe just using CLI. I'm usually doing the latter, because "it's good enough for me"™, but I know there are some editors like "vsCode" or something with useful Git integrations, if you want to go through setting that up...

BTW: I'm actually using Git and vim (editor) inside a WSL Ubuntu22 on top of my Win10, maybe a little old school, but works for me.

2023-08-10 10:59 UTC, greeneng commented on syntax/todo.php
> +                if (isset($handler) && !is_null($handler))
removed

2023-08-10 11:03 UTC, greeneng commented
Early commits were copying files from prod :)

2023-08-10 11:03 UTC, einhirn commented on syntax/todo.php
> +
Nitpicking, but please don't add empty lines if they're not absolutely neccessary. We haven't got code style guidelines yet, but don't do it... [also other places...]

2023-08-10 11:03 UTC, einhirn commented on syntax/todo.php
> +                 $data = array_merge(array ($state, 'todotitle' => $handler->todotitle, 'todoindex' => $handler->todo_index, 'todouser' => $handler->todo_user, 'checked' => $handler->checked), $handl
Missed a tab...

2023-08-10 11:05 UTC, einhirn commented on syntax/todo.php
> +        $return .= '<input type="checkbox" class="todocheckbox"'
looks like another indentation fix.

2023-08-10 11:14 UTC, runout-at commented on syntax/todo.php
> +                }
ah, maybe i forgot so send the review i wrote yesterday... sorry. should be here now.

2023-08-14 14:52 UTC, einhirn requested changes

2023-08-14 14:52 UTC, einhirn commented on syntax/todo.php
> +        }
perhaps this could just be an switch instead of if/elseif/elseif?
```
if (isset($data['priority'])) switch($data['priority']) {
  case 1:
    $priorityclass .= ' todolow';
    break;
  case 2:
    $priorityclass .= ' todomedium';
    break;
  case 3:
    $priorityclass .= ' todohigh';
    break;
}

2023-08-14 14:52 UTC, einhirn commented on syntax/todo.php
> +            $spanclass .= ' '.$bg;
[Lines 307-309]
I'm not sure whether this should be expanded. Anyway, expanding this would be part of a code refactor, not part of a feature PR: Since you don't change the function of the code, don't change it. Makes it easier to see what a PR changed exactly.

2023-08-14 14:52 UTC, einhirn commented on syntax/todo.php
> +        }
Why `$priorityclass`? why not just add it to `$spanclass` directly?

2023-08-29 14:21 UTC, greeneng commented on syntax/todo.php
> +        }
didn't add it directly to stay closer to original line order, before I decided to put everything on GitHub. I can move this section closer to first assignment $spanclass.

I changed the logic from ignoring more than 3 '!' chars, to making them 'high' priority, thence >= sign in the last 'if' operator and not switch

2023-08-29 14:22 UTC, greeneng commented on syntax/todo.php
> +            $spanclass .= ' '.$bg;
reverted, but I'm waiting for reply to previous message

2024-01-12 15:20 UTC, einhirn commented on syntax/todo.php
> +        }
Sorry for only coming back to this now...

I would follow the flow of the function - it outputs the HTML code for one TODO-Item from left to right, from top to bottom. Same with the CSS class used for priority - the code to decide which one to use should be somewhere close to where it will be inserted into the output, so you can "read along" when looking at the HTML...

Put it just below https://github.com/leibler/dokuwiki-plugin-todo/blob/49ae537f16d763f801947334f4c9697737d4affb/syntax/todo.php#L303

2024-02-01 16:17 UTC, einhirn commented
So sorry, but there are some conflicts now - please rebase.

2024-02-26 17:33 UTC, greeneng commented
Updated.
Sorry for plenty of commit messages. They were created during rebase and merge-conflict resolutions.

2024-03-06 08:30 UTC, RobertWeinmeister commented
I think you could also merge the current main branch into your branch and resolve any conflicts. This might be easier to do.

2024-05-10 14:05 UTC, closed without merging

2024-05-10 14:06 UTC, einhirn commented
I went ahead and cleaned this up into a single commit with just the needed changes.